### ISSUE TITLE
Validate the inventory state on CI

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tools#18]
It would be great if we could have `sr inv-validate` run on CI in order to pick up on state issues. Since the primary mode of interaction with the inventory is direct-push rather than PRs, this isn't perfect, though feels like a useful starting point.

**Comment by PeterJCLaw** [comment]
wrong repo

**Comment by PeterJCLaw** [comment]
(moved to https://github.com/srobo/inventory/issues/8)

**Comment by trickeydan** [comment]
FYI for the future, GitHub does now have a "Transfer Issue" button.

**Comment by PeterJCLaw** [comment]
Oh nice, where?

**Comment by trickeydan** [comment]
![](file:///tmp/issue.png)

Huh, it appears to be disabled on the `srobo` org for me. @RealOrangeOne can probably help debug that as it's likely to be a useful feature for instances such as this.

**Comment by RealOrangeOne** [comment]
I've enabled issue deletion for those with admin access to repos (disabled by default). There's nothing specifically for transfer, but I assume that would cover it.

**Comment by PeterJCLaw** [comment]
Hrm, this definitely sounds like it's an Admin thing.

I'm not sure we need issue deletion enabled; that's mainly aimed at removing security issues reported to the wrong place. I suggested we leave it disabled for now and enable it in the event that we actually need it.

**Comment by trickeydan** [comment]
> I'm not sure we need issue deletion enabled; that's mainly aimed at removing security issues reported to the wrong place. I suggested we leave it disabled for now and enable it in the event that we actually need it.

:+1:
