### ISSUE TITLE
Improvements after Sorting Weekend

### ISSUE THREAD

**Issue by trickeydan** [srobo/tools#2]
There are some gaps in the tooling that we have discovered would be useful this weekend:

- `sr inv-mv` should accept codes on `stdin`
- An auditing script
- Check-in script

**Comment by PeterJCLaw** [comment]
I ended up creating a bunch of really hacky tools to aid with kit collation: https://gist.github.com/PeterJCLaw/96ef08945e6e3299fe1d13cbaeff54ca. It would be better if we could have more direct support in the tools themselves.

Some of these are covered by the other specific improvements suggested here (for example #4), though others will need improvements to the docs around how to use the `inv-query` command.
